# Generated by Django 4.2 on 2025-04-19 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fivesquarefeets_django1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.RenameField(
            model_name='property',
            old_name='date_posted',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='author',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.IntegerField(default=0, help_text='Area in square feet'),
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='images',
            field=models.ImageField(upload_to='property_pics'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('villa', 'Villa'), ('land', 'Land'), ('commercial', 'Commercial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'property')},
        ),
    ]
